/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DatasourcesRouteImport } from './routes/datasources'
import { Route as IndexRouteImport } from './routes/index'

const DatasourcesRoute = DatasourcesRouteImport.update({
  id: '/datasources',
  path: '/datasources',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datasources': typeof DatasourcesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datasources': typeof DatasourcesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datasources': typeof DatasourcesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/datasources'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/datasources'
  id: '__root__' | '/' | '/datasources'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatasourcesRoute: typeof DatasourcesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/datasources': {
      id: '/datasources'
      path: '/datasources'
      fullPath: '/datasources'
      preLoaderRoute: typeof DatasourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatasourcesRoute: DatasourcesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
